title: MOHT Healthy Precincts
url: https://www.moht.com.sg
favicon: /images/healthy_precincts_logo_no bg.png
colors:
  primary-color: "#99b8b5"
  secondary-color: "#929292"
  media-colors:
    - title: media-color-one
      color: "#929292"
    - title: media-color-two
      color: "#99b8b5"
    - title: media-color-three
      color: "#58c0c4"
    - title: media-color-four
      color: "#58c0c4"
    - title: media-color-five
      color: "#58c0c4"
description: A Healthy Precinct provides a conducive environment, activated
  community and an integrated health and social ecosystem to support and sustain
  healthy lifestyles for all.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d236v8am3fkr6h.amplifyapp.com
prod: https://master.d236v8am3fkr6h.amplifyapp.com
shareicon: /images/healthy_precincts_logo_no bg.png
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
google_analytics_ga4: ""
resources_name: blog
