title: MOHT Healthy Precincts
url: https://www.moht.com.sg
favicon: /images/favicon-isomer.ico
colors:
  primary-color: "#6031b6"
  secondary-color: "#88b5a3"
  media-colors:
    - title: media-color-one
      color: "#88b5a3"
    - title: media-color-two
      color: "#744d9f"
    - title: media-color-three
      color: "#00838f"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
description: A Healthy Precinct provides a conducive environment, activated
  community and an integrated health and social ecosystem to support and sustain
  healthy lifestyles for all.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d236v8am3fkr6h.amplifyapp.com
prod: https://master.d236v8am3fkr6h.amplifyapp.com
shareicon: /images/isomer-logo.svg
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
google_analytics_ga4: ""
